name: "Prettier Check"
description: "[Test] Check code style with Prettier"

runs:
  using: "composite"
  steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Setup Bun cache
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Setup Prettier cache
      uses: actions/cache@v4
      with:
        path: node_modules/.cache/prettier
        key: ${{ runner.os }}-prettier-${{ hashFiles('**/*.{ts,tsx,js,jsx,json,md}', '**/prettier.config.js') }}
        restore-keys: |
          ${{ runner.os }}-prettier-

    - name: Install dependencies
      run: bun install
      shell: bash

    - name: Check code style
      run: bun prettier --cache --cache-strategy=metadata --check '**/*.{ts,tsx,js,jsx,json,md}'
      shell: bash
