name: "Type Check"
description: "Run type check with TypeScript"

runs:
  using: "composite"
  steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up pnpm
      uses: pnpm/action-setup@v2
      with:
        version: '9.10.0'

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Check types
      run: pnpm run type-check
      shell: bash
