name: "Type Check"
description: "Run type check with TypeScript"

runs:
  using: "composite"
  steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Setup Bun cache
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Setup TypeScript cache
      uses: actions/cache@v4
      with:
        path: |
          .tsbuildinfo
          node_modules/.cache/tsbuildinfo
          **/.tsbuildinfo
        key: ${{ runner.os }}-tsbuildinfo-${{ hashFiles('**/tsconfig.json', '**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-tsbuildinfo-

    - name: Install dependencies
      run: bun install
      shell: bash

    - name: Check types
      run: bun run type-check
      shell: bash
