name: "Auto-merge PR"

on:
  workflow_run:
    workflows: ["Pull Request CI"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # CIが成功した場合のみ実行
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1.6.2
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      # PRの情報を取得
      - name: Extract PR Information
        id: pr-info
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0];
            if (!pullRequest) {
              console.log('No pull request found');
              return;
            }
            
            // PRの情報をoutputsに設定
            core.setOutput('has_pr', 'true');
            core.setOutput('pr_number', pullRequest.number);

      # PRが存在する場合のみマージ処理を実行
      - name: Auto-merge PR
        if: steps.pr-info.outputs.has_pr == 'true'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_NUMBER: ${{ steps.pr-info.outputs.pr_number }}
        run: |
          # レポジトリ情報を取得
          REPO="${GITHUB_REPOSITORY}"
          
          # PRを承認
          gh pr review $PR_NUMBER --approve -R $REPO
          
          # PRをマージ
          gh pr merge $PR_NUMBER --auto --merge -R $REPO
          # レポジトリ情報を取得
          REPO="${GITHUB_REPOSITORY}"
          # PRを承認
          gh pr review $PR_NUMBER --approve
          
          # PRをマージ
          gh pr merge $PR_NUMBER --auto --merge