name: Auto Merge Dependabot PRs

on:
  workflow_run:
    workflows: ["Pull Request CI"]
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto merge Dependabot PR
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          pull-request-number: ${{ github.event.workflow_run.pull_requests[0].number }}