concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
name: Pull Request CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  # Prettierのチェック
  call-prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run Prettier Check
        uses: ./.github/actions/linter/prettier

  # ESLintのチェック
  call-eslint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ESLint Check
        uses: ./.github/actions/linter/eslint

  # TypeScriptの型チェック
  call-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run Type Check
        uses: ./.github/actions/linter/type-check

  # 単体テストの実行
  call-unit-test:
    runs-on: ubuntu-latest
    env:
      SKIP_UNIT_TEST: ${{ secrets.SKIP_UNIT_TEST }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: SKIP判定（SKIP_UNIT_TEST=trueならneutral判定）
        if: ${{ env.SKIP_UNIT_TEST == 'true' }}
        run: exit 78
      - name: Run Unit Tests
        if: ${{ env.SKIP_UNIT_TEST != 'true' }}
        uses: ./.github/actions/test/unit

  # ITAテストの実行
  call-ita-test-jra:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ITA Tests For Jra
        uses: ./.github/actions/test/ita/jra

  call-ita-test-nar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ITA Tests For Nar
        uses: ./.github/actions/test/ita/nar

  call-ita-test-overseas:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ITA Tests For Overseas
        uses: ./.github/actions/test/ita/overseas

  call-ita-test-overseas-cloudflare:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ITA Tests For Overseas
        uses: ./.github/actions/test/ita/overseas-cloudflare

  call-ita-test-keirin:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ITA Tests For Keirin
        uses: ./.github/actions/test/ita/keirin

  call-ita-test-autorace:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ITA Tests For Autorace
        uses: ./.github/actions/test/ita/autorace

  call-ita-test-boatrace:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ITA Tests For Boatrace
        uses: ./.github/actions/test/ita/boatrace