name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  # Prettierのチェック
  call-prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run Prettier Check
        uses: ./.github/actions/linter/prettier

  # ESLintのチェック
  call-eslint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ESLint Check
        uses: ./.github/actions/linter/eslint

  # TypeScriptの型チェック
  call-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run Type Check
        uses: ./.github/actions/linter/type-check

  # 単体テストの実行
  call-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run Unit Tests
        uses: ./.github/actions/test/unit

  # ITAテストの実行
  call-ita-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [
          'jra',
          'nar',
          'world',
          'keirin',
          'autorace',
          'boatrace'
        ]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ITA Tests For ${{ matrix.test }}
        uses: ./.github/actions/test/ita/${{ matrix.test }}
