name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  # prettierのチェック
  call-prettier-check:
    uses: ./.github/workflows/prettier-check.yml

  # eslintのチェック
  call-eslint-check:
    uses: ./.github/workflows/eslint-check.yml

  # 単体テストの実行
  call-unit-test:
    uses: ./.github/workflows/unit-test.yml

  # itaテストの実行
  call-ita-test:
    uses: ./.github/workflows/ita-test.yml
