name: Race Schedule Machine

on:
  schedule:
    # 日本時間の毎日5,11,17,23時に実行
    - cron: '0 2,8,14,20 * * *'
  workflow_dispatch:
    inputs:
      start-date:
        description: 'Start date (YYYY-MM-DD format)'
        required: false
      finish-date:
        description: 'Finish date (YYYY-MM-DD format)'
        required: false

env:
  CLOUDFLARE_API_PRODUCTION_URL: "${{ secrets.CLOUDFLARE_API_PRODUCTION_URL }}"

permissions:
  contents: write
  pull-requests: write

jobs:
  set-dates:
    runs-on: ubuntu-latest
    outputs:
      start-date: ${{ steps.set-dates.outputs.start-date }}
      finish-date: ${{ steps.set-dates.outputs.finish-date }}
      finish-date-for-mechanical-racing: ${{ steps.set-dates.outputs.finish-date }}
    steps:
      - name: Outputを設定
        id: set-dates
        run: |
          # 日付を計算、デフォルトは昨日から2日後
          startDate="${{ github.event.inputs.start-date }}"
          finishDate="${{ github.event.inputs.finish-date }}"
          finishDateForMechanicalRacing="$finishDate"

          # 入力がない場合のデフォルト設定
          if [ -z "$startDate" ]; then
            startDate=$(date -d "yesterday" +"%Y-%m-%d")
          fi
          if [ -z "$finishDate" ]; then
            finishDate=$(date -d "+2 day" +"%Y-%m-%d")
            finishDateForMechanicalRacing=$(date -d "+1 day" +"%Y-%m-%d")
          fi

          # GITHUB_OUTPUTを使って出力設定
          echo "start-date=$startDate" >> $GITHUB_OUTPUT
          echo "finish-date=$finishDate" >> $GITHUB_OUTPUT
          echo "finish-date-for-mechanical-racing=$finishDateForMechanicalRacing" >> $GITHUB_OUTPUT

          # デバッグ用に出力
          echo "Start Date: $startDate"
          echo "Finish Date: $finishDate"
          echo "Finish Date for Mechanical Racing: $finishDateForMechanicalRacing"

  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Start server in background
        run: |
          health_check_response=$(curl -s -o /dev/null -w "%{http_code}" ${CLOUDFLARE_API_PRODUCTION_URL}/health)

          # レスポンスチェック
          if [[ "$health_check_response" != "200" ]]; then
            echo "❌ POST request failed with status code $health_check_response"
            exit 1
          fi

  update-race-data-g:
    needs: [set-dates, health-check]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Send curl request to API
        run: |
          # 日付はset-datesで設定済み
          startDate="${{ needs.set-dates.outputs.start-date }}"
          finishDate="${{ needs.set-dates.outputs.finish-date-for-mechanical-racing }}"

          # レースデータの更新
          update_race_data_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            "${CLOUDFLARE_API_PRODUCTION_URL}/race" \
            -H "accept: */*" \
            -H "Content-Type: application/json" \
            -d "{
                  \"startDate\": \"$startDate\",
                  \"finishDate\": \"$finishDate\",
                  \"raceType\": [\"KEIRIN\", \"AUTORACE\"],
                  \"grade\": [\"GP\", \"GⅠ\", \"GⅡ\", \"GⅢ\"]
                }")

          # レスポンスチェック
          if [[ "$update_race_data_response" != "200" ]]; then
            echo "❌ POST request failed with status code $update_race_data_response"
            exit 1
          fi

  update-race-calendar-g:
    needs: [set-dates, update-race-data-g]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Send curl request to API
        run: |
          startDate="${{ needs.set-dates.outputs.start-date }}"
          finishDate="${{ needs.set-dates.outputs.finish-date-for-mechanical-racing }}"

          # カレンダーの更新
          update_race_calendar_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            "${CLOUDFLARE_API_PRODUCTION_URL}/calendar" \
            -H "accept: */*" \
            -H "Content-Type: application/json" \
            -d "{
                  \"startDate\": \"$startDate\",
                  \"finishDate\": \"$finishDate\",
                  \"raceType\": [\"KEIRIN\", \"AUTORACE\"]
                }")

          # レスポンスチェック
          if [[ "$update_race_calendar_response" != "200" ]]; then
            echo "❌ POST request failed with status code $update_race_calendar_response"
            exit 1
          fi


  update-race-data-f1:
    needs: [set-dates, health-check]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check if should run
        id: check-time
        run: |
          # 現在の時刻を取得（UTC）
          current_hour=$(date -u +%H)
          
          # 5時と13時（UTC 20時と4時）のみ実行
          if [[ "$current_hour" == "20" || "$current_hour" == "04" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
            echo "✅ Running at allowed time: ${current_hour}:00 UTC"
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
            echo "⏭️ Skipping - current time ${current_hour}:00 UTC is not 04:00 or 20:00"
          fi

      - name: Send curl request to API
        if: steps.check-time.outputs.should_run == 'true'
        run: |
          # 日付はset-datesで設定済み
          startDate="${{ needs.set-dates.outputs.start-date }}"
          finishDate="${{ needs.set-dates.outputs.finish-date-for-mechanical-racing }}"

          # レースデータの更新
          update_race_data_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            "${CLOUDFLARE_API_PRODUCTION_URL}/race" \
            -H "accept: */*" \
            -H "Content-Type: application/json" \
            -d "{
                  \"startDate\": \"$startDate\",
                  \"finishDate\": \"$finishDate\",
                  \"raceType\": [\"KEIRIN\"],
                  \"grade\": [\"FⅠ\"]
                }")

          # レスポンスチェック
          if [[ "$update_race_data_response" != "200" ]]; then
            echo "❌ POST request failed with status code $update_race_data_response"
            exit 1
          fi


  update-race-data-f2:
    needs: [set-dates, health-check]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check if should run
        id: check-time
        run: |
          # 現在の時刻を取得（UTC）
          current_hour=$(date -u +%H)
          
          # 11時と23時（UTC 2時と14時）のみ実行
          if [[ "$current_hour" == "02" || "$current_hour" == "14" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
            echo "✅ Running at allowed time: ${current_hour}:00 UTC"
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
            echo "⏭️ Skipping - current time ${current_hour}:00 UTC is not 02:00 or 14:00"
          fi

      - name: Send curl request to API
        if: steps.check-time.outputs.should_run == 'true'
        run: |
          # 日付はset-datesで設定済み
          startDate="${{ needs.set-dates.outputs.start-date }}"
          finishDate="${{ needs.set-dates.outputs.finish-date-for-mechanical-racing }}"

          # レースデータの更新
          update_race_data_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            "${CLOUDFLARE_API_PRODUCTION_URL}/race" \
            -H "accept: */*" \
            -H "Content-Type: application/json" \
            -d "{
                  \"startDate\": \"$startDate\",
                  \"finishDate\": \"$finishDate\",
                  \"raceType\": [\"KEIRIN\"],
                  \"grade\": [\"FⅡ\"]
                }")

          # レスポンスチェック
          if [[ "$update_race_data_response" != "200" ]]; then
            echo "❌ POST request failed with status code $update_race_data_response"
            exit 1
          fi

  update-race-calendar-f:
    needs: [set-dates, update-race-data-f1, update-race-data-f2]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Send curl request to API
        run: |
          startDate="${{ needs.set-dates.outputs.start-date }}"
          finishDate="${{ needs.set-dates.outputs.finish-date-for-mechanical-racing }}"

          # カレンダーの更新
          update_race_calendar_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            "${CLOUDFLARE_API_PRODUCTION_URL}/calendar" \
            -H "accept: */*" \
            -H "Content-Type: application/json" \
            -d "{
                  \"startDate\": \"$startDate\",
                  \"finishDate\": \"$finishDate\",
                  \"raceType\": [\"KEIRIN\", \"AUTORACE\"]
                }")

          # レスポンスチェック
          if [[ "$update_race_calendar_response" != "200" ]]; then
            echo "❌ POST request failed with status code $update_race_calendar_response"
            exit 1
          fi
