name: Validate Branch Name

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch name starts with feature/
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ ! "$BRANCH_NAME" =~ ^feature/ ]]; then
            echo "エラー: ブランチ名はfeature/で始めてください。現在: $BRANCH_NAME"
            exit 1
          fi
        shell: bash
