name: World Horse Race Schedule Batch

on:
  schedule:
    - cron: '0 21 * * *' # 毎日21時に実行
  workflow_dispatch:
    inputs:
      start-date:
        description: 'Start date (YYYY-MM-DD format)'
        required: false
      finish-date:
        description: 'Finish date (YYYY-MM-DD format)'
        required: false

jobs:
  world-race:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Send curl request to API
        env:
          API_PRODUCTION_URL: ${{ secrets.API_PRODUCTION_URL }}
        run: |
          # 日付を計算、デフォルトは昨日から2日後
          startDate="${{ github.event.inputs.start-date }}"
          finishDate="${{ github.event.inputs.finish-date }}"

          # 入力がない場合のデフォルト設定
          if [ -z "$startDate" ]; then
            startDate=$(date -d "yesterday" +"%Y-%m-%d")
          fi
          if [ -z "$finishDate" ]; then
            finishDate=$(date -d "+2 days" +"%Y-%m-%d")
          fi

          # レースデータの更新
          update_race_data_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            "${API_PRODUCTION_URL}/api/races/world/race" \
            -H "accept: */*" \
            -H "Content-Type: application/json" \
            -d "{
                  \"startDate\": \"$startDate\",
                  \"finishDate\": \"$finishDate\"
                }")

          # レスポンスチェック
          if [[ "$update_race_data_response" != "200" ]]; then
            echo "❌ POST request failed with status code $update_race_data_response"
            exit 1
          fi

          # カレンダーの更新
          update_race_calendar_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            "${API_PRODUCTION_URL}/api/races/world/calendar" \
            -H "accept: */*" \
            -H "Content-Type: application/json" \
            -d "{
                  \"startDate\": \"$startDate\",
                  \"finishDate\": \"$finishDate\"
                }")

          # レスポンスチェック
          if [[ "$update_race_calendar_response" != "200" ]]; then
            echo "❌ POST request failed with status code $update_race_calendar_response"
            exit 1
          fi

          echo "✅ API requests succeeded with startDate: $startDate and finishDate: $finishDate"
