on:
  schedule:
    - cron: '0 21 * * *' # 毎日21時に実行
  workflow_dispatch: # 手動トリガーを許可

jobs:
  world-race:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Send curl request to API
        env:
          API_PRODUCTION_URL: ${{ secrets.API_PRODUCTION_URL }}
        run: |
          # 日付を計算
          startDate=$(date -d "yesterday" +"%Y-%m-%d")
          finishDate=$(date -d "+2 days" +"%Y-%m-%d")

          # update race data
          update_race_data_response=$(curl -s -o /dev/null -w "%{http_code}" -X 'POST' \
            '${API_PRODUCTION_URL}/api/races/world/race' \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
                  "startDate": ${startDate},
                  "finishDate": ${finishDate}
                }')

          # update race data response check
          if [[ "$update_race_data_response" != "200" ]]; then
            echo "❌ POST request failed with status code $update_race_data_response"
            exit 1
          fi

          # update race calendar
          update_race_calendar_response=$(curl -s -o /dev/null -w "%{http_code}" -X 'POST' \
            '${API_PRODUCTION_URL}/api/races/world/calendar' \
            -H 'accept: */*' \
            -H 'Content-Type: application/json' \
            -d '{
                  "startDate": ${startDate},
                  "finishDate": ${finishDate}
                }')

          # update race calendar response check
          if [[ "$update_race_calendar_response" != "200" ]]; then
            echo "❌ POST request failed with status code $update_race_calendar_response"
            exit 1
          fi
